version: "3.8"
services:
  web:
    image: nginx
    ports:
      - 80:80
    deploy:
      mode: replicated
      replicas: 4
      restrt_policy: 
        condition: on-failure
      placement:
        constraints: [node.role == worker]     # nginx will always run on worker nodes
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]    # visualizer will always run on manager node
