---
apiVersion: v1
kind: service
metadata:
  name: my_service
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 30021
  selector:
    app: nginx

